import argparse

parser = argparse.ArgumentParser(
        description='generate config files based on template')
parser.add_argument("--config", required=True,
        help="path to the configuration toml file")
args = parser.parse_args()

network_names = ["TH", "THA", "THABET", "THABIT", "THACH", "THACHER", "THACKER", "THACKERAY", "THACKERSON", "THACKERY", "THACKRAH", "THACKRAY", "THACKREY", "THACKSTON", "THADANI", "THADEN", "THAEMERT", "THAETE", "THAGARD", "THAGGARD", "THAI", "THAIN", "THAIS", "THAKAR", "THAKE", "THAKER", "THAKKAR", "THAKKER", "THAKOR", "THAKORE", "THAKRAR", "THAKUR", "THAL", "THALACKER", "THALE", "THALER", "THALHAMMER", "THALHEIMER", "THALKEN", "THALL", "THALLER", "THALMAN", "THALMANN", "THAM", "THAMAN", "THAMANN", "THAMERT", "THAMES", "THAMM", "THAMMAVONG", "THAMMAVONGSA", "THAMS", "THAN", "THANDI", "THANE", "THANG", "THANH", "THANKACHAN", "THANNER", "THANOS", "THAO", "THAPA", "THAPAR", "THAR", "THARAKAN", "THARALDSON", "THARES", "THARIN", "THARNISH", "THARP", "THARPE", "THARPS", "THARRETT", "THARRINGTON", "THATCH", "THATCHER", "THATE", "THATER", "THAU", "THAUER", "THAUT", "THAW", "THAWLEY", "THAXTER", "THAXTON", "THAY", "THAYER", "THAYN", "THAYNE", "THE", "THEAD", "THEADO", "THEAGENE", "THEAKER", "THEAKSTON", "THEAL", "THEALL", "THEARD", "THEBARGE", "THEBAUD", "THEBEAU", "THEBERGE", "THEBO", "THEDE", "THEDENS", "THEDFORD", "THEE", "THEECK", "THEEDE", "THEEL", "THEER", "THEES", "THEESFELD", "THEETGE", "THEIBERT", "THEIGE", "THEIL", "THEILACKER", "THEILE", "THEILEN", "THEILER", "THEILIG", "THEILING", "THEILMAN", "THEIMER", "THEIN", "THEIS", "THEISEN", "THEISING", "THEISMANN", "THEISS", "THEISSEN", "THELANDER", "THELE", "THELEMANN", "THELEMAQUE", "THELEN", "THELIN", "THELL", "THELLMAN", "THELUSMA", "THELWELL", "THEM", "THEMELIS", "THEMER", "THEMM", "THEN", "THENG", "THENNES", "THENO", "THEO", "THEOBALD", "THEOBOLD", "THEODOR", "THEODORAKIS", "THEODORE", "THEODORIDIS", "THEODOROPOULOS", "THEODOROU", "THEODOS", "THEODOSIS", "THEODOSOPOULOS", "THEODULE", "THEOHARIS", "THEOPHILE", "THEOPHILUS", "THEORET", "THEOS", "THERESA", "THERIAC", "THERIAQUE", "THERIAULT", "THERIEN", "THERING", "THERIOT", "THERKELSEN", "THERKILDSEN", "THERMAN", "THERMIDOR", "THERMITUS", "THERMOS", "THERN", "THEROFF", "THERON", "THEROS", "THEROUX", "THERRELL", "THERRES", "THERRIAN", "THERRIAULT", "THERRIEN", "THERVIL", "THERY", "THESENVITZ", "THESIER", "THESING", "THESSEN", "THET", "THETFORD", "THEUER", "THEUERKAUF", "THEUNE", "THEUNISSEN", "THEURER", "THEURET", "THEUS", "THEUSCH", "THEUT", "THEVENIN", "THEVENOT", "THEVIS", "THEW", "THEWES", "THEWLIS", "THEWS", "THEXTON", "THEYE", "THEYS", "THI", "THIAGARAJAN", "THIAM", "THIARA", "THIAS", "THIBADEAU", "THIBADO", "THIBAUDEAU", "THIBAULT", "THIBAUT", "THIBEAU", "THIBEAULT", "THIBEAUX", "THIBEDEAU", "THIBERT", "THIBIDEAU", "THIBO", "THIBODAUX", "THIBODEAU", "THIBODEAUX", "THIBODO", "THIBOU", "THIBOUTOT", "THICH", "THICK", "THICKLIN", "THIE", "THIEBAUD", "THIEBAUT", "THIEDE", "THIEKE", "THIEKEN", "THIEL", "THIELBAR", "THIELE", "THIELEMAN", "THIELEMANN", "THIELEMIER", "THIELEN", "THIELER", "THIELGES", "THIELING", "THIELKE", "THIELKER", "THIELKING", "THIELMAN", "THIELMANN", "THIELS", "THIELSEN", "THIEM", "THIEMAN", "THIEMANN", "THIEME", "THIEMER", "THIEN", "THIENEMAN", "THIENES", "THIER", "THIERBACH", "THIERER", "THIERET", "THIERFELDER", "THIERJUNG", "THIERMAN", "THIEROFF", "THIEROLF", "THIERRY", "THIERS", "THIERY", "THIES", "THIESCHAFER", "THIESEN", "THIESFELD", "THIESING", "THIESS", "THIESSE", "THIESSEN", "THIEU", "THIFFAULT", "THIGPEN", "THIGPIN", "THILGES", "THILL", "THILLET", "THILMAN", "THILMANY", "THILMONY", "THILTGEN", "THIM", "THIMESCH", "THIMM", "THIMMES", "THIMMESCH", "THIMMIG", "THIMONS", "THIMSEN", "THIND", "THINER", "THING", "THINGELSTAD", "THINGVOLD", "THINN", "THINNES", "THIO", "THIRION", "THIRKIELD", "THIRKILL", "THIRSK", "THIRTYACRE", "THIRY", "THISSELL", "THISSEN", "THISTIE", "THISTLE", "THISTLETHWAITE", "THISTLEWOOD", "THIVENER", "THIVIERGE", "THIXTON", "THO", "THOAMS", "THOBE", "THOBURN", "THODE", "THODEN", "THODY", "THOE", "THOEL", "THOELE", "THOELKE", "THOEMKE", "THOEN", "THOENE", "THOENEN", "THOENI", "THOENNES", "THOENSEN", "THOENY", "THOGERSEN", "THOGMARTIN", "THOI", "THOITS", "THOLE", "THOLEN", "THOLL", "THOM", "THOMA", "THOMACK", "THOMAE", "THOMALLA", "THOMAN", "THOMANN", "THOMAS", "THOMASEN", "THOMASIAN", "THOMASMA", "THOMASON", "THOMASSEE", "THOMASSEN", "THOMASSIAN", "THOMASSIE", "THOMASSON", "THOMASTON", "THOMAZIN", "THOMBS", "THOME", "THOMECZEK", "THOMEN", "THOMER", "THOMERSON", "THOMES", "THOMETZ", "THOMEY", "THOMFORDE", "THOMISEE", "THOMISON", "THOMKINS", "THOMLEY", "THOMLINSON", "THOMLISON", "THOMMA", "THOMMEN", "THOMMES", "THOMOPOULOS", "THOMOSON", "THOMPKINS", "THOMPSEN", "THOMPSOM", "THOMPSON", "THOMS", "THOMSEN", "THOMSON", "THOMSPON", "THOMURE", "THON", "THONE", "THONEN", "THONG", "THONGKHAM", "THONGSAVANH", "THONI", "THONN", "THONY", "THOOFT", "THOPSON", "THOR", "THORBAHN", "THORBJORNSEN", "THORBOURNE", "THORBURN", "THORDARSON", "THORDSEN", "THORE", "THOREEN", "THORELL", "THOREN", "THORESEN", "THORESON", "THORFINNSON", "THORIN", "THORINGTON", "THORKELSON", "THORKILDSEN", "THORLAKSON", "THORLEY", "THORMAHLEN", "THORMAN", "THORMANN", "THORN", "THORNAL", "THORNBER", "THORNBERG", "THORNBERRY", "THORNBLAD", "THORNBLOOM", "THORNBROUGH", "THORNBRUE", "THORNBRUGH", "THORNBURG", "THORNBURGH", "THORNBURY", "THORNDIKE", "THORNDYKE", "THORNE", "THORNELL", "THORNER", "THORNES", "THORNG", "THORNGATE", "THORNGREN", "THORNHILL", "THORNING", "THORNLEY", "THORNOCK", "THORNQUIST", "THORNS", "THORNSBERRY", "THORNSBURG", "THORNSBURY", "THORNSLEY", "THORNTON", "THORNWELL", "THOROGOOD", "THOROMAN", "THOROUGHGOOD", "THOROUGHMAN", "THORP", "THORPE", "THORSBY", "THORSELL", "THORSEN", "THORSHEIM", "THORSLAND", "THORSNESS", "THORSON", "THORSTAD", "THORSTED", "THORSTEINSON", "THORSTEN", "THORSTENSEN", "THORSTENSON", "THORUD", "THORUP", "THORVILSON", "THORWART", "THOSS", "THOSTENSON", "THOTA", "THOU", "THOUIN", "THOUNE", "THOUSAND", "THOUVENIN", "THOW", "THRAEN", "THRAILKILL", "THRALL", "THRALLS", "THRAMER", "THRAMS", "THRAN", "THRANE", "THRAPP", "THRASH", "THRASHER", "THREADGILL", "THREAT", "THREATS", "THREATT", "THREATTE", "THREATTS", "THREET", "THREETON", "THREETS", "THRELFALL", "THRELKEL", "THRELKELD", "THREM", "THREN", "THRESHER", "THRESS", "THRIFT", "THRO", "THROCKMORTON", "THROENER", "THROESCH", "THROGMORTON", "THROM", "THRON", "THRONDSON", "THRONE", "THRONEBERRY", "THRONEBURG", "THRONSON", "THROOP", "THROPE", "THROPP", "THROW", "THROWER", "THRUMAN", "THRUN", "THRUSH", "THRUSTON", "THU", "THUDIUM", "THUE", "THUENTE", "THUESEN", "THUESON", "THUET", "THUKRAL", "THUL", "THULIN", "THULL", "THULLEN", "THUM", "THUMA", "THUMAN", "THUMANN", "THUMM", "THUMMA", "THUMMEL", "THUMS", "THUMSER", "THUN", "THUNBERG", "THUNDER", "THUNDERCLOUD", "THUNDERHAWK", "THUNE", "THUNELL", "THUNSTROM", "THUOT", "THUOTTE", "THUR", "THURAU", "THURBER", "THURBY", "THURGOOD", "THURIN", "THURINGER", "THURK", "THURKETTLE", "THURLBY", "THURLEY", "THURLKILL", "THURLO", "THURLOW", "THURM", "THURMAN", "THURMER", "THURMES"]
#["MA", "MAA", "MAACK", "MAAE", "MAAG", "MAAHS", "MAAK", "MAAKESTAD", "MAALI", "MAALOUF", "MAAN", "MAANUM", "MAAR", "MAAS", "MAASCH", "MAASEN", "MAASKE", "MAASS", "MAASSEN", "MAAT", "MAATMAN", "MAATTA", "MABALOT", "MABARY", "MABASA", "MABB", "MABBETT", "MABBITT", "MABBOTT", "MABBUTT", "MABE", "MABEE", "MABEL", "MABEN", "MABERRY", "MABERY", "MABES", "MABEUS", "MABEY", "MABIE", "MABILE", "MABIN", "MABINE", "MABINI", "MABINS", "MABIS", "MABLE", "MABLES", "MABLEY", "MABON", "MABONE", "MABRA", "MABRAY", "MABREY", "MABROUK", "MABRY", "MABSON", "MABUS", "MABUTAS", "MAC", "MACA", "MACABEO", "MACADAM", "MACADAMS", "MACADANGDANG", "MACAFEE", "MACAGNONE", "MACAIONE", "MACAK", "MACAL", "MACALA", "MACALALAD", "MACALI", "MACALIK", "MACALINO", "MACALINTAL", "MACALISTER", "MACALLISTER", "MACALMA", "MACALPINE", "MACALUSO", "MACAN", "MACANAS", "MACANCELA", "MACAPAGAL", "MACAPINLAC", "MACARAEG", "MACARAIG", "MACARANAS", "MACARENO", "MACARI", "MACARIO", "MACARO", "MACARTHUR", "MACARTHY", "MACARTNEY", "MACARY", "MACAS", "MACASAET", "MACASIEB", "MACASKILL", "MACASPAC", "MACATANGAY", "MACATEE", "MACAULAY", "MACAULEY", "MACAVOY", "MACAY", "MACAYA", "MACBAIN", "MACBEAN", "MACBETH", "MACBLANE", "MACBRIDE", "MACCA", "MACCABE", "MACCABEE", "MACCALL", "MACCALLA", "MACCALLUM", "MACCANI", "MACCARI", "MACCARIO", "MACCARO", "MACCARONE", "MACCARRONE", "MACCARTER", "MACCARTHY", "MACCARTNEY", "MACCHI", "MACCHIA", "MACCHIARELLA", "MACCHIAROLI", "MACCHIO", "MACCHIONE", "MACCIA", "MACCINI", "MACCIO", "MACCIOLI", "MACCLELLAN", "MACCO", "MACCOLL", "MACCOLLUM", "MACCONNELL", "MACCORD", "MACCORMACK", "MACCORMICK", "MACCOY", "MACCRACKEN", "MACCREADY", "MACCUBBIN", "MACCULLOCH", "MACCURDY", "MACDANIEL", "MACDERMID", "MACDERMOTT", "MACDIARMID", "MACDONALD", "MACDONELL", "MACDONNELL", "MACDONOUGH", "MACDOUGAL", "MACDOUGALL", "MACDOWALL", "MACDOWELL", "MACDUFF", "MACDUFFIE", "MACE", "MACEACHEN", "MACEACHERN", "MACEDA", "MACEDO", "MACEDONIA", "MACEDONIO", "MACEIRA", "MACEJAK", "MACEJKA", "MACEK", "MACELROY", "MACEMORE", "MACENTEE", "MACEO", "MACER", "MACERA", "MACERI", "MACERO", "MACEWAN", "MACEWEN", "MACEY", "MACEYKO", "MACFADDEN", "MACFADYEN", "MACFALL", "MACFARLAN", "MACFARLAND", "MACFARLANE", "MACFEE", "MACFIE", "MACGEORGE", "MACGIBBON", "MACGILL", "MACGILLIS", "MACGILLIVARY", "MACGILLIVRAY", "MACGILVRAY", "MACGOWAN", "MACGOWN", "MACGREGOR", "MACGUIRE", "MACH", "MACHA", "MACHAC", "MACHACEK", "MACHADO", "MACHAIN", "MACHAJ", "MACHAJEWSKI", "MACHAK", "MACHAL", "MACHALA", "MACHALEK", "MACHAMER", "MACHAN", "MACHARIA", "MACHART", "MACHCINSKI", "MACHEEL", "MACHEK", "MACHEL", "MACHELL", "MACHEMER", "MACHEN", "MACHER", "MACHESKY", "MACHESNEY", "MACHI", "MACHIA", "MACHICEK", "MACHICOTE", "MACHIDA", "MACHIELA", "MACHIN", "MACHINSKI", "MACHLAN", "MACHLEIT", "MACHLER", "MACHLIN", "MACHMER", "MACHNIAK", "MACHNICKI", "MACHNIK", "MACHO", "MACHOL", "MACHOLD", "MACHOLL", "MACHOLZ", "MACHON", "MACHORRO", "MACHOS", "MACHOTKA", "MACHOVEC", "MACHOVINA", "MACHOVSKY", "MACHOWICZ", "MACHOWSKI", "MACHT", "MACHTEMES", "MACHUCA", "MACHUGA", "MACHUT", "MACHUTA", "MACIA", "MACIAG", "MACIAK", "MACIAS", "MACIASZEK", "MACIE", "MACIEJ", "MACIEJEWSKI", "MACIEJKO", "MACIEL", "MACIER", "MACIK", "MACINA", "MACINDOE", "MACINNES", "MACINNIS", "MACINO", "MACINTIRE", "MACINTOSH", "MACINTYRE", "MACIOCE", "MACIOCH", "MACIOCI", "MACIOLEK", "MACIOROWSKI", "MACIS", "MACISAAC", "MACIVER", "MACIVOR", "MACK", "MACKALL", "MACKAMAN", "MACKAY", "MACKE", "MACKECHNIE", "MACKEDANZ", "MACKEEN", "MACKEL", "MACKELL", "MACKELLAR", "MACKELPRANG", "MACKEN", "MACKENDRICK", "MACKENNA", "MACKENROTH", "MACKENS", "MACKENSEN", "MACKENTHUN", "MACKENZIE", "MACKER", "MACKERETH", "MACKERT", "MACKES", "MACKESEY", "MACKESSY", "MACKESY", "MACKEY", "MACKI", "MACKIE", "MACKIEWICZ", "MACKILLOP", "MACKIN", "MACKINDER", "MACKINLAY", "MACKINNEY", "MACKINNON", "MACKINS", "MACKINSON", "MACKINTOSH", "MACKISON", "MACKLE", "MACKLEM", "MACKLEN", "MACKLER", "MACKLES", "MACKLEY", "MACKLIN", "MACKLING", "MACKNER", "MACKNEY", "MACKNIGHT", "MACKO", "MACKOOL", "MACKOUL", "MACKOWIAK", "MACKOWSKI", "MACKRELL", "MACKRILL", "MACKS", "MACKSEY", "MACKSON", "MACKSOUD", "MACKUS", "MACKY", "MACLACHLAN", "MACLAIN", "MACLAINE", "MACLANE", "MACLAREN", "MACLAUCHLAN", "MACLAUGHLIN", "MACLAURIN", "MACLAURY", "MACLAY", "MACLEAN", "MACLEAY", "MACLEISH", "MACLELLAN", "MACLENNAN", "MACLEOD", "MACLIN", "MACLURE", "MACMAHON", "MACMANUS", "MACMARTIN", "MACMASTER", "MACMATH", "MACMICHAEL", "MACMILLAN", "MACMILLEN", "MACMILLIAN", "MACMINN", "MACMULLAN", "MACMULLEN", "MACMULLIN", "MACMURDO", "MACMURRAY", "MACNAB", "MACNABB", "MACNAIR", "MACNALLY", "MACNAMARA", "MACNAMEE", "MACNAUGHT", "MACNAUGHTON", "MACNEAL", "MACNEIL", "MACNEILL", "MACNEVIN", "MACNICHOL", "MACNICOL", "MACNIVEN", "MACNUTT", "MACO", "MACOLINO", "MACOM", "MACOMB", "MACOMBER", "MACOMSON", "MACON", "MACONE", "MACOUBRIE", "MACOY", "MACPEEK", "MACPHAIL", "MACPHEE", "MACPHERSON", "MACQUARRIE", "MACQUEEN", "MACRAE", "MACRANDER", "MACREADY", "MACRI", "MACRINA", "MACRIS", "MACRITCHIE", "MACRO", "MACROBERTS", "MACSHANE", "MACSWAIN", "MACTAGGART", "MACTAVISH", "MACUCH", "MACUGA", "MACUMBER", "MACURA", "MACURAK", "MACURDY", "MACVANE", "MACVEAN", "MACVEIGH", "MACVICAR", "MACVITTIE", "MACWAN", "MACWHINNIE", "MACWHORTER", "MACWILLIAM", "MACWILLIAMS", "MACY", "MACZIEWSKI", "MACZKA", "MACZKO", "MACZUGA", "MADA", "MADAFFARI", "MADAIO", "MADAJ", "MADAK", "MADALA", "MADALENA", "MADALINSKI", "MADAMA", "MADAMBA", "MADAN", "MADANAT", "MADANI", "MADAR", "MADARA", "MADARANG", "MADARAS", "MADARASZ", "MADARIAGA", "MADARIS", "MADARY", "MADAUS", "MADAY", "MADAYAG", "MADDALENA", "MADDALONE", "MADDALONI", "MADDAMMA", "MADDELA", "MADDEN", "MADDERN", "MADDEROM", "MADDERRA", "MADDEX", "MADDI", "MADDIE", "MADDIGAN", "MADDIN", "MADDING", "MADDISON", "MADDIX", "MADDLE", "MADDOCK", "MADDOCKS", "MADDON", "MADDOUX", "MADDOX", "MADDOY", "MADDREY", "MADDRON", "MADDRY", "MADDUX", "MADDY", "MADE", "MADEIRA", "MADEIROS", "MADEJ", "MADEJA", "MADEL", "MADELEY", "MADELINE", "MADELL", "MADEN", "MADENFORD", "MADEO", "MADER", "MADERA", "MADERAZO", "MADERE", "MADERIA", "MADERO", "MADEROS", "MADES", "MADEWELL", "MADEY", "MADGE", "MADGETT", "MADGWICK", "MADHANI", "MADHAVAN", "MADI", "MADIA", "MADIAS", "MADICK", "MADIGAN", "MADILL", "MADINE", "MADINGER", "MADIS", "MADISON", "MADIX", "MADKINS", "MADL", "MADLAND", "MADLANGBAYAN", "MADLEM", "MADLENER", "MADLER", "MADLEY", "MADLIN", "MADLINGER", "MADLOCK", "MADNICK", "MADOFF", "MADOLE", "MADON", "MADONADO", "MADONIA", "MADONNA", "MADOR", "MADORE", "MADORIN", "MADORMA", "MADORSKY", "MADOW", "MADPLUME", "MADRAK", "MADRANO", "MADRAY", "MADRAZO", "MADRE", "MADREN", "MADREY", "MADRIAGA", "MADRID", "MADRIGAL", "MADRIGALES", "MADRIL", "MADRILES", "MADRILL", "MADRIS", "MADRIZ", "MADRO", "MADRON", "MADRONA", "MADRU", "MADRUENO", "MADRUGA", "MADRY", "MADSEN", "MADSON", "MADU", "MADUENA", "MADUENO"]
#["NAAB", "NAAKTGEBOREN", "NAAMAN", "NAAR", "NAAS", "NAASZ", "NAATZ", "NAB", "NABA", "NABARRETE", "NABARRO", "NABAVI", "NABB", "NABBEFELD", "NABEL", "NABER", "NABERHAUS", "NABERS", "NABHAN", "NABHOLZ", "NABI", "NABINGER", "NABITY", "NABLE", "NABLO", "NABONG", "NABOR", "NABORS", "NABOURS", "NABOZNY", "NABULSI", "NACAR", "NACARATO", "NACARIO", "NACCA", "NACCARATO", "NACCARI", "NACCI", "NACE", "NACEY", "NACHAZEL", "NACHBAR", "NACHMAN", "NACHREINER", "NACHT", "NACHTIGAL", "NACHTIGALL", "NACHTMAN", "NACHTRAB", "NACHTRIEB", "NACHTSHEIM", "NACHTWEY", "NACIANCENO", "NACINO", "NACINOVICH", "NACION", "NACIONALES", "NACK", "NACKE", "NACKERS", "NACKLEY", "NACLERIO", "NACOL", "NACUA", "NACY", "NADA", "NADAL", "NADALIN", "NADAR", "NADARAJAH", "NADDAF", "NADDEO", "NADDY", "NADE", "NADEAU", "NADEEM", "NADEL", "NADELL", "NADELLA", "NADELMAN", "NADEN", "NADER", "NADERI", "NADERMANN", "NADIG", "NADIN", "NADING", "NADIR", "NADKARNI", "NADLER", "NADOLNY", "NADOLSKI", "NADOLSKY", "NADON", "NADRATOWSKI", "NADREAU", "NADROWSKI", "NADY", "NADZAM", "NADZAN", "NAEA", "NAEEM", "NAEF", "NAEGEL", "NAEGELE", "NAEGELI", "NAEGELIN", "NAEGER", "NAEGLE", "NAEOLE", "NAERT", "NAES", "NAESS", "NAESSENS", "NAEVE", "NAEYAERT", "NAFE", "NAFF", "NAFFZIGER", "NAFTALI", "NAFTEL", "NAFTZGER", "NAFUS", "NAFZGER", "NAFZIGER", "NAG", "NAGA", "NAGAI", "NAGAL", "NAGAMATSU", "NAGAMINE", "NAGAN", "NAGANO", "NAGANUMA", "NAGAO", "NAGAOKA", "NAGAR", "NAGARAJ", "NAGARAJA", "NAGARAJAN", "NAGASAKO", "NAGASAWA", "NAGASE", "NAGASHIMA", "NAGATA", "NAGATANI", "NAGAYAMA", "NAGBE", "NAGEL", "NAGELBERG", "NAGELE", "NAGELHOUT", "NAGELKIRK", "NAGELL", "NAGENGAST", "NAGEOTTE", "NAGER", "NAGERA", "NAGEY", "NAGG", "NAGGAR", "NAGI", "NAGIB", "NAGIN", "NAGL", "NAGLE", "NAGLER", "NAGLEY", "NAGLICH", "NAGLIERI", "NAGO", "NAGODE", "NAGORNY", "NAGORSKI", "NAGOWSKI", "NAGPAL", "NAGRA", "NAGTALON", "NAGUIB", "NAGUIT", "NAGURNEY", "NAGY", "NAH", "NAHA", "NAHABEDIAN", "NAHAL", "NAHAR", "NAHAS", "NAHASS", "NAHAY", "NAHHAS", "NAHIGIAN", "NAHILL", "NAHINU", "NAHLEN", "NAHLIK", "NAHM", "NAHMIAS", "NAHODIL", "NAHON", "NAHORNIAK", "NAHRA", "NAHRGANG", "NAHRSTEDT", "NAHRWOLD", "NAHUM", "NAI", "NAICKER", "NAIDA", "NAIDITCH", "NAIDOO", "NAIDU", "NAIFEH", "NAIG", "NAIHE", "NAII", "NAIK", "NAIL", "NAILE", "NAILER", "NAILL", "NAILLING", "NAILLON", "NAILON", "NAILOR", "NAILS", "NAIM", "NAIMAN", "NAIMI", "NAIMO", "NAIMOLI", "NAIN", "NAING", "NAIPO", "NAIR", "NAIRN", "NAIRNE", "NAISBITT", "NAISER", "NAISH", "NAISMITH", "NAITO", "NAJA", "NAJAFI", "NAJAM", "NAJAR", "NAJARIAN", "NAJARRO", "NAJDA", "NAJDEK", "NAJDOWSKI", "NAJEM", "NAJERA", "NAJI", "NAJIB", "NAJIM", "NAJJAR", "NAJM", "NAJMAN", "NAJMI", "NAJOR", "NAK", "NAKA", "NAKABAYASHI", "NAKACHI", "NAKADA", "NAKAGAKI", "NAKAGAWA", "NAKAHARA", "NAKAI", "NAKAJI", "NAKAJIMA", "NAKAMA", "NAKAMATSU", "NAKAMICHI", "NAKAMOTO", "NAKAMURA", "NAKANISHI", "NAKANO", "NAKAO", "NAKAOKA", "NAKASATO", "NAKASH", "NAKASHIAN", "NAKASHIMA", "NAKASONE", "NAKATA", "NAKATANI", "NAKATSU", "NAKATSUKA", "NAKAWATASE", "NAKAYA", "NAKAYAMA", "NAKAZATO", "NAKAZAWA", "NAKHLA", "NAKHLEH", "NAKI", "NAKIS", "NAKKEN", "NAKO", "NAKOA", "NAKONECHNY", "NAKONECZNY", "NAKOS", "NALBACH", "NALBANDIAN", "NALBANDYAN", "NALBONE", "NALDER", "NALE", "NALEPA", "NALEPKA", "NALER", "NALES", "NALESNIK", "NALETTE", "NALEVANKO", "NALEWAY", "NALEZNY", "NALK", "NALL", "NALLE", "NALLEN", "NALLEY", "NALLI", "NALLS", "NALLY", "NALTY", "NALVEN", "NAM", "NAMA", "NAMAHOE", "NAMAN", "NAMANNY", "NAMAZI", "NAMBA", "NAMBIAR", "NAMBO", "NAMDAR", "NAME", "NAMER", "NAMES", "NAMETH", "NAMEY", "NAMI", "NAMIAS", "NAMIE", "NAMKEN", "NAMKOONG", "NAMKUNG", "NAMM", "NAMMOUR", "NAMOKI", "NAMOWICZ", "NAMVAR", "NAN", "NANA", "NANAN", "NANAVATI", "NANAYAKKARA", "NANCARROW", "NANCE", "NANCY", "NAND", "NANDA", "NANDI", "NANDIN", "NANDLAL", "NANDWANI", "NANDY", "NANES", "NANEY", "NANEZ", "NANFITO", "NANG", "NANGIA", "NANGLE", "NANI", "NANIA", "NANK", "NANKE", "NANKERVIS", "NANKIN", "NANKIVELL", "NANN", "NANNA", "NANNEMAN", "NANNEN", "NANNENGA", "NANNERY", "NANNEY", "NANNI", "NANNIE", "NANNINGA", "NANNINI", "NANNY", "NANO", "NANOS", "NANSEL", "NANSEN", "NANSON", "NANTAIS", "NANTHAVONG", "NANTON", "NANTZ", "NANZ", "NAO", "NAONE", "NAOR", "NAOUM", "NAP", "NAPARSTEK", "NAAB", "NAAKTGEBOREN", "NAAMAN", "NAAR", "NAAS", "NAASZ", "NAATZ", "NAB", "NABA", "NABARRETE", "NABARRO", "NABAVI", "NABB", "NABBEFELD", "NABEL", "NABER", "NABERHAUS", "NABERS", "NABHAN", "NABHOLZ", "NABI", "NABINGER", "NABITY", "NABLE", "NABLO", "NABONG", "NABOR", "NABORS", "NABOURS", "NABOZNY", "NABULSI", "NACAR", "NACARATO", "NACARIO", "NACCA", "NACCARATO", "NACCARI", "NACCI", "NACE", "NACEY", "NACHAZEL", "NACHBAR", "NACHMAN", "NACHREINER", "NACHT", "NACHTIGAL", "NACHTIGALL", "NACHTMAN", "NACHTRAB", "NACHTRIEB", "NACHTSHEIM", "NACHTWEY", "NACIANCENO", "NACINO", "NACINOVICH", "NACION", "NACIONALES", "NACK", "NACKE", "NACKERS", "NACKLEY", "NACLERIO", "NACOL", "NACUA", "NACY", "NADA", "NADAL", "NADALIN", "NADAR", "NADARAJAH", "NADDAF", "NADDEO", "NADDY", "NADE", "NADEAU", "NADEEM", "NADEL", "NADELL", "NADELLA", "NADELMAN", "NADEN", "NADER", "NADERI", "NADERMANN", "NADIG", "NADIN", "NADING", "NADIR", "NADKARNI", "NADLER", "NADOLNY", "NADOLSKI", "NADOLSKY", "NADON", "NADRATOWSKI", "NADREAU", "NADROWSKI", "NADY", "NADZAM", "NADZAN", "NAEA", "NAEEM", "NAEF", "NAEGEL", "NAEGELE", "NAEGELI", "NAEGELIN", "NAEGER", "NAEGLE", "NAEOLE", "NAERT", "NAES", "NAESS", "NAESSENS", "NAEVE", "NAEYAERT", "NAFE", "NAFF", "NAFFZIGER", "NAFTALI", "NAFTEL", "NAFTZGER", "NAFUS", "NAFZGER", "NAFZIGER", "NAG", "NAGA", "NAGAI", "NAGAL", "NAGAMATSU", "NAGAMINE", "NAGAN", "NAGANO", "NAGANUMA", "NAGAO", "NAGAOKA", "NAGAR", "NAGARAJ", "NAGARAJA", "NAGARAJAN", "NAGASAKO", "NAGASAWA", "NAGASE", "NAGASHIMA", "NAGATA", "NAGATANI", "NAGAYAMA", "NAGBE", "NAGEL", "NAGELBERG", "NAGELE", "NAGELHOUT", "NAGELKIRK", "NAGELL", "NAGENGAST", "NAGEOTTE", "NAGER", "NAGERA", "NAGEY", "NAGG", "NAGGAR", "NAGI", "NAGIB", "NAGIN", "NAGL", "NAGLE", "NAGLER", "NAGLEY", "NAGLICH", "NAGLIERI", "NAGO", "NAGODE", "NAGORNY", "NAGORSKI", "NAGOWSKI", "NAGPAL", "NAGRA", "NAGTALON", "NAGUIB", "NAGUIT", "NAGURNEY", "NAGY", "NAH", "NAHA", "NAHABEDIAN", "NAHAL", "NAHAR", "NAHAS", "NAHASS", "NAHAY", "NAHHAS", "NAHIGIAN", "NAHILL", "NAHINU", "NAHLEN", "NAHLIK", "NAHM", "NAHMIAS", "NAHODIL", "NAHON", "NAHORNIAK", "NAHRA", "NAHRGANG", "NAHRSTEDT", "NAHRWOLD", "NAHUM", "NAI", "NAICKER", "NAIDA", "NAIDITCH", "NAIDOO", "NAIDU", "NAIFEH", "NAIG", "NAIHE", "NAII", "NAIK", "NAIL", "NAILE", "NAILER", "NAILL", "NAILLING", "NAILLON", "NAILON", "NAILOR", "NAILS", "NAIM", "NAIMAN", "NAIMI", "NAIMO", "NAIMOLI", "NAIN", "NAING", "NAIPO", "NAIR", "NAIRN", "NAIRNE", "NAISBITT", "NAISER", "NAISH", "NAISMITH", "NAITO", "NAJA", "NAJAFI", "NAJAM", "NAJAR", "NAJARIAN", "NAJARRO", "NAJDA", "NAJDEK", "NAJDOWSKI", "NAJEM", "NAJERA", "NAJI", "NAJIB", "NAJIM", "NAJJAR", "NAJM", "NAJMAN", "NAJMI", "NAJOR", "NAK", "NAKA", "NAKABAYASHI", "NAKACHI", "NAKADA", "NAKAGAKI", "NAKAGAWA", "NAKAHARA", "NAKAI", "NAKAJI", "NAKAJIMA", "NAKAMA", "NAKAMATSU", "NAKAMICHI", "NAKAMOTO", "NAKAMURA", "NAKANISHI", "NAKANO", "NAKAO", "NAKAOKA", "NAKASATO", "NAKASH", "NAKASHIAN", "NAKASHIMA", "NAKASONE", "NAKATA", "NAKATANI", "NAKATSU", "NAKATSUKA", "NAKAWATASE", "NAKAYA", "NAKAYAMA", "NAKAZATO", "NAKAZAWA", "NAKHLA", "NAKHLEH", "NAKI", "NAKIS", "NAKKEN", "NAKO", "NAKOA", "NAKONECHNY", "NAKONECZNY", "NAKOS", "NALBACH", "NALBANDIAN", "NALBANDYAN", "NALBONE", "NALDER", "NALE", "NALEPA", "NALEPKA", "NALER", "NALES", "NALESNIK", "NALETTE", "NALEVANKO", "NALEWAY", "NALEZNY", "NALK", "NALL", "NALLE", "NALLEN", "NALLEY", "NALLI", "NALLS", "NALLY", "NALTY", "NALVEN", "NAM", "NAMA", "NAMAHOE", "NAMAN", "NAMANNY", "NAMAZI", "NAMBA", "NAMBIAR", "NAMBO", "NAMDAR", "NAME", "NAMER", "NAMES", "NAMETH", "NAMEY", "NAMI", "NAMIAS", "NAMIE", "NAMKEN", "NAMKOONG", "NAMKUNG", "NAMM", "NAMMOUR", "NAMOKI", "NAMOWICZ", "NAMVAR", "NAN", "NANA", "NANAN", "NANAVATI", "NANAYAKKARA", "NANCARROW", "NANCE", "NANCY", "NAND", "NANDA", "NANDI", "NANDIN", "NANDLAL", "NANDWANI", "NANDY", "NANES", "NANEY", "NANEZ", "NANFITO", "NANG", "NANGIA", "NANGLE", "NANI", "NANIA", "NANK", "NANKE", "NANKERVIS", "NANKIN", "NANKIVELL", "NANN", "NANNA", "NANNEMAN", "NANNEN", "NANNENGA", "NANNERY", "NANNEY", "NANNI", "NANNIE", "NANNINGA", "NANNINI", "NANNY", "NANO", "NANOS", "NANSEL", "NANSEN", "NANSON", "NANTAIS", "NANTHAVONG", "NANTON", "NANTZ", "NANZ", "NAO", "NAONE", "NAOR", "NAOUM", "NAP", "NAPARSTEK", "NAPE", "NAPER", "NAPERT", "NAPIER", "NAPIERALA", "NAPIERALSKI", "NAPIERKOWSKI", "NAPIERSKI", "NAPIORKOWSKI", "NAPIWOCKI", "NAPLE", "NAPLES", "NAPODANO", "NAPOLEON", "NAPOLEONE", "NAPOLEONI", "NAPOLES", "NAPOLETANO", "NAPOLI", "NAPOLIELLO", "NAPOLILLO", "NAPOLITAN", "NAPOLITANO", "NAPORA", "NAPP", "NAPPA", "NAPPE", "NAPPER", "NAPPI", "NAPPIER", "NAPPO", "NAPUE", "NAPUTI", "NAQUI", "NAQUIN", "NAQVI", "NARA", "NARAG", "NARAGHI", "NARAGON", "NARAIN", "NARAINE", "NARAMORE", "NARAN", "NARANG", "NARANGO", "NARANJO", "NARASIMHAN", "NARAYAN", "NARAYANA", "NARAYANAN", "NARAYANASWAMY", "NARBUT", "NARBY", "NARCHO", "NARCISCO", "NARCISE", "NARCISI", "NARCISO", "NARCISSE", "NARD", "NARDACCI", "NARDECCHIA", "NARDELLA", "NARDELLI", "NARDELLO", "NARDI", "NARDIELLO", "NARDIN", "NARDINE", "NARDINI", "NARDO", "NARDOLILLO", "NARDONE", "NARDONI", "NARDOZZA", "NARDOZZI", "NARDUCCI", "NARDULLI", "NARDUZZI", "NARDY", "NARE", "NARED", "NAREDO", "NAREHOOD", "NAREL", "NARENS", "NARES", "NAREWSKI", "NAREY", "NAREZ", "NARGI", "NARIMATSU", "NARIN", "NARINE", "NARIO", "NARITA", "NARKIEWICZ", "NARLOCH", "NARLOCK", "NARMORE", "NARO", "NAROG", "NARON", "NAROWSKI", "NARR", "NARRA", "NARRAGON", "NARRAMORE", "NARRELL", "NARRIS", "NARRO", "NARRON", "NARROW", "NARTATEZ", "NARTEY", "NARTINEZ", "NARTKER", "NARTOWICZ", "NARULA", "NARUM", "NARUP", "NARUS", "NARVA", "NARVAES", "NARVAEZ", "NARVAIS", "NARVAIZ", "NARVESON", "NARWOLD", "NARY", "NAS", "NASA", "NASALROAD", "NASAR", "NASARIO", "NASATKA", "NASBY", "NASCA", "NASCIMENTO", "NASCO", "NASE", "NASEEF", "NASEEM", "NASEER", "NASELLI", "NASELLO", "NASEMAN", "NASER", "NASH", "NASHAWATY", "NASHED", "NASI", "NASIATKA", "NASIF", "NASIM", "NASIR", "NASIRI", "NASLUND", "NASMAN", "NASO", "NASON", "NASRALLA", "NASRALLAH", "NASRI", "NASS", "NASSAR", "NASSAU", "NASSE", "NASSEF", "NASSEN", "NASSER", "NASSERI", "NASSET", "NASSI", "NASSIF", "NASSIFF", "NASSIR", "NASSIRI", "NASSO", "NASSOUR", "NAST", "NASTA", "NASTACIO", "NASTALLY", "NASTARI", "NASTASE", "NASTASI", "NASTASIA", "NASTI", "NASTO", "NASTRI", "NASTRO", "NASUTA", "NASUTI", "NASWORTHY", "NAT", "NATA", "NATAL", "NATALE", ]

extension='.toml'
layer_number =  [3, 4] #0, 1, 2
layer_neurons = [128, 256, 512, 1024]
biases = [#{
    #"name": "Bailey",
    #"value": [True, True]
#}, 
#{
#    "name": "Beatrice",
#    "value": [True, False]
#}, 
{
    "name": "Bella",
    "value": [False, False]
}]
activations = [{
    "name": "Adam",
    "value": ["relu", "relu"]
}
#{
#    "name": "Alice",
#    "value": ["relu", "linear"]
#}, #{
    #"name": "Anthony",
    #"value": ["linear", "linear"]
#}
]
learning_rate =[{ 
    "name": "Rory",
    "value": 0.01,
}
, {
    "name": "Rose",
    "value": 0.001,
}
]

ex_max = [
{
    "name": "Emory",
    "max": 8,
    "value": 8e-9,
},
{
    "name": "Emily",
    "max": 80,
    "value": 8e-8,
},
#{
#    "name": "Edward",
#    "max": 1,
#    "value": 64e-9,
#}
]

label_max = [
    {
    "name": "Lynn",
    "max": 10,
    "value": 0.1
},
{
    "name": "Lisa",
    "max": 100,
    "value": 0.01

},
#{
#    "name": "Lynsey",
#    "max": 1,
#    "value": 1

#}
]

#[NeuralNetwork]
#ModelName = "~model_name~"
#DataFileNames = ["long_ht_n_g","long_ht_n_3p","long_ht_n_7g"]
#EvalFileNames = ["long_ht_g", "long_ht_3p"]
#Layers = ~layers~ #[2048, 1024, 512, 512]
#Biases = ~biases~ #["False", "False", "False", "False", "False"]
#Activations = ~activations~ #["relu", "relu", "relu", "relu", "linear"]
#LearningRate = ~learning_rate~ #0.001
#DefaultMaxEx = ~default_max_ex~ #8e-9
#DefaultRatio = ~default_ratio~ #0.1

#generate packages:

default_settings={
    "model_name":"",
    "layers":"",
    "biases":"",
    "activations":"",
    "learning_rate":"",
    "default_max_ex": "",
    "default_ratio":""
}

settings_list = []
global ni
ni = 0
def buildNetwork (layer_str, biases_str, acts_str, layer_num, bia, act):
    global ni 
    if (layer_num >= 1):
        for lneu in layer_neurons:
            new_layer_str = layer_str+'"'+str(lneu)+'"'+", "
            new_biases_str = biases_str+'"'+str(bia['value'][0])+'"'+","
            new_acts_str = acts_str+'"'+str(act['value'][0])+'"'+","
            buildNetwork ( new_layer_str, new_biases_str, new_acts_str, layer_num - 1,bia, act )
    else:
        new_layer_str = layer_str+"] "
        new_biases_str = biases_str+'"'+str(bia['value'][1])+'"'+"]"
        new_acts_str = acts_str+'"'+str(act['value'][1])+'"'+"]"
        ni = ni+1
        
            #biases_str = biases_str+str(bia["value"][0])+","
        print("----------------------ni", ni)
        for em in ex_max:
            for lm in label_max:
                for lr in learning_rate:
                        name = em['name']+"-"+lm['name']+"-"+lr["name"]+"-"+act['name']+"-"+bia['name'] 
                        st = default_settings.copy() 
                        st["model_name"]=name+"-"+network_names[ni]
                        st["layers"]=new_layer_str
                        st["biases"]=new_biases_str
                        st["activations"]=new_acts_str
                        st["learning_rate"]=str(lr["value"])
                        st["default_max_ex"]=str(em["value"])
                        st["default_ratio"]=  str(lm["value"])
                        settings_list.append(st)
                        print(st)
                                
#buildNetwork("[", "[", 1, [True, False], "xxx")
print(len(network_names))
for act in activations:
    for bia in biases:
        ni = 0
        for lnum in layer_number: #0, 1, 2, 3, 4
            buildNetwork("[", "[", "[", lnum, bia, act)

print(len(settings_list))

placeholders = ["model_name",
    "layers",
    "biases",
    "activations",
    "learning_rate",
    "default_max_ex",
    "default_ratio"]

with open('run_grid_search.sh', 'w') as bf:
    bf.write('set -x\n')

    for st in settings_list:
        with open(args.config+"_template"+extension) as fp:
            outfilename = "task1-"+st["model_name"]+extension
            with open(outfilename, 'w' ) as fo:
                line = fp.readline()
                while line:
                    for key in placeholders:
                        line = line.replace("~"+key+"~", st[key])
                    fo.write(line)
                    line = fp.readline()
    
        bf.write("python ../train/grid_search_controller.py --config config/{}\n".format(outfilename))
    