[Slab]
Transformation = [
   ['TranslateZ', 'RotateY', 'TranslateX'],
   [10.0, 28.0, 40.0]]
Volume = [[-12.0, 100.0], [-75.0, 75.0], [-12.0, 0.0]]

[Chamfer]
x0 = 35.0

[[Output]]
Type = 'STL'
LinearDeflection = 0.1   # mm
IsRelative = false
AngularDeflection = 20.0  # deg
Filename = 'out/shield.stl'
